version: 1
formatters:
  default:
    format: "%(asctime)s - %(levelname)s - %(message)s"
handlers:
  file:
    class: logging.FileHandler
    filename: "app.log"
    formatter: default
    level: INFO
root:
  level: INFO
  handlers: [file]